### ISSUE TITLE
Bug: Android - Unable to find component class com.urbanairship.location.AirshipLocationManager

### ISSUE THREAD

**Issue by AE1NS** [urbanairship/airship-location-cordova#3]
The technical support told me, that this plugin is mandatory for using Gimbal location events with Airship. Am I correct, that its mandatory for both, iOS and Android?

Regarding this doc https://docs.airship.com/platform/cordova/location/ I just see an iOS part for setup, but maybe there is just nothing more todo for Android. Or is this plugin only needed for iOS? Because there is also an Android implementation. Thats a little but unclear for me.

When I install this plugin (together with the latest urbanairship-cordova) and call "setLocationEnabled", I get the following error in Android:
```
E/UALib-Cordova: Action failed to execute: setLocationEnabled
    java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.urbanairship.cordova.AirshipLocationPlugin$1.run(AirshipLocationPlugin.java:74)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
     Caused by: java.lang.IllegalArgumentException: Unable to find component class com.urbanairship.location.AirshipLocationManager
        at com.urbanairship.UAirship.requireComponent(UAirship.java:1026)
        at com.urbanairship.location.AirshipLocationManager.shared(AirshipLocationManager.java:100)
        at com.urbanairship.cordova.AirshipLocationPlugin.setLocationEnabled(AirshipLocationPlugin.java:105)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.urbanairship.cordova.AirshipLocationPlugin$1.run(AirshipLocationPlugin.java:74) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:920)
```

Is there maybe any incompatibility with the airship sdk version?

**Comment by Ulrico972** [comment]
Hello @AE1NS 
I have to tell you there was a mistake on the technical support recommandation.
This plugin is not mandatory to use the location and region events on Airship. This plugin is actually deprecated and planed to be removed later.
So instead, you should just use our Gimbal integration that I think you already know about (https://github.com/urbanairship/cordova-gimbal-bridge). This Gimbal plugin triggers the Airship region events.

**Comment by AE1NS** [comment]
Makes it of course more easy :) thanks for your response!
